name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
     PYTHONPATH: ${{github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install  dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_template.txt
          pip install pytest
          - name: Start FastAPI server
        run: uvicorn src.betynic.server:app --host 127.0.0.1 --port 8000 &
      - name: Wait for server
        run: sleep 3
      - name: Test API endpoint
        run: |
          python - <<EOF
          import requests
          resp = requests.post(
              "http://127.0.0.1:8000/liability/",
              json={"stake": 100, "lay_odds": 3.0}
          )
          assert resp.status_code == 200
          assert abs(resp.json()["liability"] - 10.0) < 1e-6
          EOF

      - name: Run unit tests
        run: pytest -q
